export const KAFKA_TEST_TOPIC = 'KAFKA_TEST_TOPIC';
export const KAFKA_FILE_UPLOAD = 'KAFKA_FILE_UPLOAD';
export const KAFKA_FILE_TRAIN_SUCCESS = 'KAFKA_FILE_TRAIN_SUCCESS';
export const KAFKA_GENERATE_TEXT_VIA_PROMPT = 'KAFKA_GENERATE_TEXT_VIA_PROMPT';
export const KAFKA_TOPIC_SEARCH = 'KAFKA_TOPIC_SEARCH';
export const KAFKA_TOPIC_SEARCH_RESPONSE = 'KAFKA_TOPIC_SEARCH_RESPONSE';
export const KAFKA_EMBED_REDO = 'KAFKA_EMBED_REDO';